/*Get Subsequences
Given a string, we have to find out all subsequences of it.

You have to complete the function generateSubsequence that returns a list of all subsequences sorted lexically and it should not contain empty strings.

Note: A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Input Format
The first line of input contains a string s

Output Format
print all the subsequences of given string in sorted order

Example
Input

abc
Output

a
ab
abc
ac
b
bc
c */

package RecursuionArrayList;
import java.io.*;
import java.util.*;

public class SubSequences {
    public static ArrayList<String> generateSubsequences(String str)
    {
        ArrayList<String> ans = new ArrayList<>();
        helper(str,ans,"",0);
        Collections.sort(ans);
        return ans;
    }

    public static void helper(String str, ArrayList<String> ans,
                              String subSeq, int idx) {
        if (idx >= str.length()) {
            if (subSeq != "") {
                ans.add(subSeq);
            }
            return;
        }
        helper(str,ans,subSeq,idx+1);
        helper(str,ans,subSeq+str.charAt(idx),idx+1);

    }
	public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String s;
        s = sc.nextLine();
        ArrayList<String> res = generateSubsequences(s);
        for(int i=0;i<res.size();i++){
            System.out.println(res.get(i));
        }
    }
}
